### ISSUE TITLE
Senders reference i filnavn på ack/nack meldinger

### ISSUE THREAD

**Issue by kjell77** [bitsnorge/e-tinglysing-afpant#15]
Fikk et innspill fra Evry om at det hadde vært enklere å filterere mottatte ack/nack forsendelser dersom disse alltid inneholder f.eks sendersReference (fra manifest.xml i avsenders forsendelse). Her mener jeg det vil være fornuftig å formattere filnavn til å inkludere dette, men pt er det ikke krav til filnavn i afpant spec. Burde vi hatt et slikt krav? Og evt kun introdusere dette for ack/nack filer da det er mindre sannsynlighet for at dette vil medføre endringsbehov for eksisterende avsender-banker i prod (Nordea, Ambita)?

**Comment by JonEgilH** [comment]
Ikke krise fra oss egentlig, dette dukket opp når jeg hadde rotet til sendersRef så jeg ikke fant igjen det jeg lette etter. Nå fungerer det egentlig helt fint. Så hvis ingen andre ser nytten kan man bare droppe dette for oss.

**Comment by kjell77** [comment]
ok :) da tenker jeg vi kan ha som anbefaling å inkludere senderReference i filnavn men ikke lar det være et krav inntil videre hvertfall.
