### ISSUE TITLE
Fakturamottaker

### ISSUE THREAD

**Issue by JonEgilH** [bitsnorge/e-tinglysing-afpant#16]
I følgebrevet som går til Kartverket når man skal pantsette kan man angi fakturamottaker.
Det eksisterer ikke noe felt for dette i dagens AFPant grensesnitt.
Jeg foreslår at man legger til dette som en not mandatory property der vi sender inn andre variable, BrokerServiceInitiation.Manifest.PropertyList

f,eks
<h2>Manifest metadata (BrokerServiceInitiation.Manifest.PropertyList)</h2>

Manifest key | Type | Required | Beskrivelse
------------- | ---- | --------- | -----------
invoiceReceiverNo|String|No|Gyldig orgnummer, 9 siffer. Mottaker av faktura for tinglysingsgebyr. Angis når mottaker avviker fra panthaver.

**Comment by JonEgilH** [comment]
Denne er det vist ikke behov for lenger så da slipper vi å tenkte på det.

**Comment by ArildFlatland** [comment]
Og sett fra et bankperspektiv er det alltid megleren som skal gjennomføre tinglysing av pantedokumentet som sendes inn fra banken. Megleren skal også være ansvarlig for tinglysingsgebyret. Derfor var ikke dette tatt med i den opprinnelige spesifikasjonen.
