### ISSUE TITLE
Intensjon: Tegnsett og filnavn

### ISSUE THREAD

**Issue by javaguruen** [bitsnorge/e-tinglysing-afpant#27]
Hei

Finner ikke at tegnsettet på XML-filene i intensjonsmeldingene er spesifisert. Er det en standard på dette i Altinn/Afpant? Når vi skal konvertere fra byte-array til String ved nedlasting (og opplasting), så må vi angi et tegnsett. Det står vanligvis også et tegnsett spesifisert i headeren i XML-filen, burde ikke dette være standardisert og spesifisert? Vet ikke om dette må være det samme som brukes ved konvertering mellom string og byte-array ved inn- og utpakking.

Videre ser jeg ikke at det er spesifisert en navnekonvensjon på XML-filene som skal ligge inne i zip-filen. Hadde det vært en fordel eller vil det alltid bare komme en manifest.xml og en fil til?

**Comment by paal-havnevik** [comment]
teknisk møte 06.januar 2020:
- anbefaler utf-8 encoding
- mottaker må takle at filen er encodet både med og uten BOM (byte order mark)
