### ISSUE TITLE
Ny meldingstype: Utarbeide spesifikasjon for intensjon om e-tinglysing

### ISSUE THREAD

**Issue by paal-havnevik** [bitsnorge/e-tinglysing-afpant#4]
**Målsetning**
Mulighet for bank å spørre megler om nåværende status på bruk av e-tinglysing.
Mulighet for megler å pushe endringer i status på bruk av e-tinglysing til bank.
Mulighet for bank å fortelle megler om at e-tinglysing ikke er mulig (f.eks ved realkausjon).
Mulighet for bank å fortelle megler om låneavtale er inngått
 
Det vil i hovedsak være megler som bestemmer hvilken metode som skal benyttes (papir eller elektronisk), men kjøpers bank som spør megler først.

Avsender av meldingen må inkludere sin gjeldende intensjon (elektronisk eller papirtinglysing).

1 type NACK:
- Vi finner ikke eiendommen (ukjent registerenhet)

1 type ACK, som også inneholder gjeldende status:
- Vi har funnet eiendommen, rutet riktig, og mottaker har en av følgende intensjoner: elektronisk | papir
 
Papirsaker må gis forrang - den av partene som sier at det blir papirsak må "vinne" - dette må også kommuniseres på fornftig vis ut i UI til brukeren. Det bør samtidig være mulighet for manuell koordinering mellom bank-megler i tilfelle brukerfeil/feil valg.

**Eksempel**: 
- megler indikerer e-tinglysing
- kjøper har kommnisert til megler at hun er av den oppfatning at hun skal e-signere lånepapirer og sitt pantedokument i sin bank
- kjøpers bank sender like vel intensjonsmelding med status 'papirtinglysing' (pga feil valg i banksystem)
- megler må gjøres oppmerksom på at saken nå blir papirbasert, men må kunne velge å undersøke (telefon, email) med kjøpers bank om dette stemmer
- kjøpers bank gjøres oppmerksom på feil valg og endrer til 'elektronisk tinglysing', og ny intensjonsmelding sendes
- megler + bank er enige om 'elektronisk tinglysing'
**Krav til ruting (meglersystem)**
- Nesten tilsvarende krav som for ruting av kjøpers pantedokument
- Mottaker må tillate forespørsler om intensjon hvor kun 1 av debitor/kjøper matcher med det som er registrert i meglersystemet (i motsetning til ruting av kjøpers pantedokument som krever 1:1 match). 

**Krav til mottaker (meglersystem)**
- ved endring i status (papir | elektronisk) må det automatisk kringkastes en oppdatert intensjonsmelding til alle banker/avsendere som tidligere har forespurt om intensjon på den aktuelle saken.

**Dataelementer: request**
Mottakers organisasjonsnummer
(Oppdragsnummer)
Registerenhet (matrikkeldetaljer)
Låneavtale inngått (ja | nei)
Gjeldende intensjon (elektronisk | papir)

Request sendes til et gitt organisasjonsnummer + oppdragsidentifikator(er).
Det må håndteres at forespørselen kan sendes til enten meglerforetaket eller oppdragets oppgjørsforetak (tilsvarende som ruting av pantedokument)

**Dataelementer: response**
Oppdragsnummer
Adresse
Registerenhet (matrikkeldetaljer)
Saksbehandlere (megler, ansvarig megler)
Oppgjørsansvarlig (foretak, avdeling, (oppgjørsmedarbeider))
Gjeldende intensjon (elektronisk | papir)

**Comment by paal-havnevik** [comment]
fra arild@nordea: mulig for bank å indikere om låneavtale allerede er inngått (signert) -> øker sannsynligheten for hvilken bank som skal finansiere kjøperen.

**Comment by paal-havnevik** [comment]
Terje@Ambita - ønsker å se på om kjøpekontrakt meldingstypen vil være tilstrekkelig for å formidle intensjon (begge veier?)

**Comment by JonEgilH** [comment]
Vi har ikke spesifisert hva som skal inngå i disse meldingene bortsett fra intensjon om eTinglysning ja/nei. 
Vi bør få inn at navn, epost og telefon på saksbehandler både i bank og hos megler inngår i svar/forespørsler slik at man får elektronisk inn i systemet hvem som er "motpart". Selvom megler system svarer NEI til eTinglysning bør megler sine kontakt opplysninger følge svaret.

**Comment by paal-havnevik** [comment]
i forhold til krav om ruting - ikke bruke  "Parter"-typen (for mange valg), men snevre inn til å bruke Kjopere-typen.

**Comment by paal-havnevik** [comment]
Når megler skal sende Intensjonsendring til bank så har i utgangspunktet banken ingen muligheter for å rute meldingen basert kun på registerenhet og parter (kjøperne). 
Her må bankens saksnummer være med for at banken skal ha en sjanse til å rute meldingen til korrekt lånesak. 

Dette saksnummeret må angis først av bank i 'IntensjonFraBank.Avsender.Referanse'-feltet.
Deretter må megler bruke 'IntensjonssvarFraMegler.Mottaker.Referanse'-feltet for at banken skal ha en sjanse til å rute meldingen til korrekt lånesak.

Deretter ved statusendring fra megler må bankens saksnummer angis i 'Intensjonsendring.Mottaker.Referanse'-feltet. 


--------------------

Det også være naturlig for megler å inkludere sin egen referanse i 'IntensjonssvarFraMegler.Avsender.Referanse'-feltet og i 'Intensjonsendring.Avsender.Referanse'.
